-- Quick seed script that creates a sample user and posts
-- This script works independently and doesn't require existing users

-- First, let's ensure we have the basic tables
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid not null primary key,
  full_name text,
  avatar_url text,
  title text,
  company text,
  verified boolean default false
);

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_premium boolean default false,
  price numeric(10, 2),
  metrics jsonb,
  attachment jsonb,
  job_posting jsonb
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Create policies (drop first if they exist)
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Public posts are viewable by everyone." ON public.posts;

CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

CREATE POLICY "Public posts are viewable by everyone."
  ON public.posts FOR SELECT
  USING ( true );

-- Clear existing sample data
DELETE FROM public.posts WHERE user_id IN (
  SELECT id FROM public.profiles WHERE full_name IN ('Sarah Chen', 'Marcus Rodriguez', 'Emma Thompson', 'Alex Kim', 'Jordan Lee')
);
DELETE FROM public.profiles WHERE full_name IN ('Sarah Chen', 'Marcus Rodriguez', 'Emma Thompson', 'Alex Kim', 'Jordan Lee');

-- Insert sample profiles
INSERT INTO public.profiles (id, full_name, avatar_url, title, company, verified) VALUES
  ('550e8400-e29b-41d4-a716-446655440001', 'Sarah Chen', '/placeholder.svg?height=40&width=40', 'Founder & CEO', 'TechFlow', true),
  ('550e8400-e29b-41d4-a716-446655440002', 'Marcus Rodriguez', '/placeholder.svg?height=40&width=40', 'Co-founder', 'GrowthLabs', true),
  ('550e8400-e29b-41d4-a716-446655440003', 'Emma Thompson', '/placeholder.svg?height=40&width=40', 'Head of Engineering', 'EcoTech', false),
  ('550e8400-e29b-41d4-a716-446655440004', 'Alex Kim', '/placeholder.svg?height=40&width=40', 'Founder', 'DeployFast', true),
  ('550e8400-e29b-41d4-a716-446655440005', 'Jordan Lee', '/placeholder.svg?height=40&width=40', 'Serial Entrepreneur', 'Venture Studio', true);

-- Insert sample posts
INSERT INTO public.posts (user_id, content, is_premium, price, metrics, attachment, job_posting, created_at) VALUES
  (
    '550e8400-e29b-41d4-a716-446655440001',
    '🚀 Milestone Alert! We just hit $50K MRR after 8 months of building in public. Here''s what we learned about product-led growth and why we''re doubling down on our community strategy. #BuildInPublic',
    false,
    null,
    '{"mrr": "$50,000", "growth": "+25%"}',
    null,
    null,
    NOW() - INTERVAL '2 hours'
  ),
  (
    '550e8400-e29b-41d4-a716-446655440002',
    'The hardest part about fundraising isn''t the pitch deck - it''s maintaining team morale during the process. Here''s how we kept our team motivated during our Series A... 🧵',
    true,
    5.00,
    null,
    '{"type": "pdf", "title": "Series A Fundraising Playbook", "gated": true}',
    null,
    NOW() - INTERVAL '4 hours'
  ),
  (
    '550e8400-e29b-41d4-a716-446655440003',
    'We''re hiring! Looking for a Senior Full-Stack Developer to join our mission of making sustainability accessible to everyone. Remote-first, competitive equity package 🌱 #Hiring #Jobs',
    false,
    null,
    null,
    null,
    '{"title": "Senior Full-Stack Developer", "location": "Remote", "type": "Full-time"}',
    NOW() - INTERVAL '6 hours'
  ),
  (
    '550e8400-e29b-41d4-a716-446655440004',
    'Just closed our seed round! 🎉 $2M to revolutionize how developers deploy applications. Huge thanks to our investors and early customers who believed in our vision. Now the real work begins...',
    false,
    null,
    '{"funding": "$2M", "stage": "Seed"}',
    null,
    null,
    NOW() - INTERVAL '8 hours'
  ),
  (
    '550e8400-e29b-41d4-a716-446655440005',
    'Hot take: Most startups fail not because of product-market fit, but because of founder-market fit. You need to be obsessed with the problem you''re solving, not just the solution. Thoughts? 🤔',
    false,
    null,
    null,
    null,
    null,
    NOW() - INTERVAL '12 hours'
  );

-- Success message
SELECT 'Successfully seeded newsfeed with sample posts!' as result;
